MAX_LENGTH_CARD_NAME = 30
MAX_LENGTH_GROUP_NAME = 20
MAX_LENGTH_SHOP_NAME = 30
MAX_LENGTH_CARD_NUMBER = 40
MAX_LENGTH_COLOR = 16
MAX_LENGTH_ENCODING_TYPE = 30
MAX_STATISTICS_FROM_FRONT = None
CODE128 = 'code128'
CODE39 = 'code39'
UPC_A = 'upc-a'
UPC_E = 'upc-e'
EAN_13 = 'ean-13'
EAN_8 = 'ean-8'
QR_код = 'qr-kod'
ENCODING_TYPE = (
    (CODE128, 'CODE128'),
    (CODE39, 'CODE39'),
    (UPC_A, 'UPC-A'),
    (UPC_E, 'UPC-E'),
    (EAN_13, 'EAN-13'),
    (EAN_8, 'EAN-8'),
    (QR_код, 'QR-код'),
)
