FROM node:18-alpine AS builder
WORKDIR /app
RUN apk update && apk add --no-cache git \
    && git clone -b testing https://github.com/Online-discount-card-service/odcs-frontend.git . \
    && npm install \
    && npm ci \
    && npm run build \
    && npm cache clean --force \
    && cp -r dist result_build
