FROM node:18-alpine AS builder
WORKDIR /app
RUN apk update && apk add --no-cache git \
    && git clone -b testing https://github.com/Online-discount-card-service/odcs-frontend.git .
COPY package*.json ./
RUN npm ci
COPY . ./
RUN npm run build
CMD cp -r dist/. result_build
