version: '3.8'

services:
  db:
    image: postgres:15-alpine
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile_front
    volumes:
      - ./frontend-shared:/app/result_build

  backend:
    build: ../backend/
    env_file: ./.env
    restart: always
    command: >
      sh -c "
        sleep 5 &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn backend.wsgi:application --bind 0:8000
      "
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/static/media/
#      - data:/app/data/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend-shared:/usr/share/nginx/html
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
    pg_data:
    media:
    static:
    data:
