version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:14.9-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  django:
    image: guestagain/osdc_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media

  nginx:
    image: nginx:1.24.0
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/staticfiles
      - media:/app/media