# Generated by Django 4.1 on 2023-11-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Введите пароль', max_length=255, verbose_name='Пароль'),
        ),
    ]
