# Generated by Django 4.1 on 2023-11-15 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона после +7 начинается с 9', regex='^([9]{1}[0-9]{9})?$')]),
        ),
    ]
