# Generated by Django 4.1 on 2023-12-01 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Имя может содержать только буквы, пробелы и спецсимволы.', regex='^[a-zA-Zа-яА-ЯёЁ\\s\\S]{1,60}$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Номер телефона после +7 начинается с 9', regex='^\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
