# Generated by Django 4.1 on 2023-12-16 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁ\\ \\!@#$%^&*`_+{}\\[\\].?~\\\\/\\-=|\\"\']+$', message='Имя может содержать только буквы, пробелы и спецсимволы.')], verbose_name='Имя'),
        ),
    ]
