# Generated by Django 3.2.22 on 2023-11-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название магазина', max_length=20, verbose_name='Название магазина')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления карты')),
                ('image_card', models.ImageField(help_text='Загрузите изображение', upload_to='card/', verbose_name='Изображение карты')),
                ('image_gtin', models.ImageField(blank=True, help_text='Загрузите изображение штрих-кода', upload_to='gtin/', verbose_name='Изображение штрих-кода')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=20, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': ('Категория',),
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название магазина', max_length=20, verbose_name='Название магазина')),
                ('logo', models.ImageField(help_text='Загрузите логотип магазина', upload_to='shop/', verbose_name='Лого магазина')),
                ('group', models.ManyToManyField(to='core.Group', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_favourites', to='core.card')),
            ],
            options={
                'verbose_name': 'Список избранного',
                'verbose_name_plural': 'Список избранного',
                'ordering': ('user',),
            },
        ),
    ]
