# Generated by Django 4.1 on 2023-11-14 17:56

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название карты', max_length=30, unique=True, verbose_name='Название карты')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления карты')),
                ('image_card', models.ImageField(blank=True, help_text='Загрузите изображение', upload_to='card/', verbose_name='Изображение карты')),
                ('card_number', models.CharField(blank=True, help_text='Введите номер карты', max_length=40, verbose_name='Номер карты')),
                ('barcode_number', models.CharField(blank=True, help_text='Введите номер штрих-кода', max_length=40, verbose_name='Номер штрих-кода')),
                ('encoding_type', models.CharField(choices=[('code128', 'CODE128'), ('code39', 'CODE39'), ('upc-a', 'UPC-A'), ('upc-e', 'UPC-E'), ('ean-13', 'EAN-13'), ('ean-8', 'EAN-8'), ('qr-kod', 'QR-код')], default='ean-13', max_length=30, verbose_name='Тип кодировки бар-кода карты')),
                ('usage_counter', models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Количество использования карты')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=20, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': ('Категория',),
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назовите карту', max_length=30, verbose_name='Название карты')),
                ('logo', models.ImageField(help_text='Загрузите логотип магазина', upload_to='shop/', verbose_name='Лого магазина')),
                ('color', models.CharField(blank=True, max_length=16, validators=[core.validators.validate_color_format], verbose_name='Цвет магазина')),
                ('validation', models.BooleanField(blank=True, default=False, verbose_name='Критерий валидации магазина')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(blank=True, default=True, verbose_name='Принадлежность')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_favourites', to='core.card', verbose_name='Карты')),
            ],
            options={
                'verbose_name': 'Список избранного',
                'verbose_name_plural': 'Список избранного',
                'ordering': ('user',),
            },
        ),
    ]
