# Generated by Django 3.2.22 on 2023-10-31 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добовления карты')),
                ('image_card', models.ImageField(help_text='Загрузите изображение', upload_to='card/', verbose_name='Изображение карты')),
                ('image_gtin', models.ImageField(blank=True, help_text='Загрузите изображение штрих-кода', upload_to='gtin/', verbose_name='Изображение штрих-кода')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Введите индентификатор категории', unique=True, verbose_name='Индентификатор категории')),
            ],
            options={
                'verbose_name': ('Категория',),
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название магазина', max_length=200, verbose_name='Название магазина')),
                ('logo', models.ImageField(help_text='Загрузите логотип магазина', upload_to='shop/', verbose_name='Лого магазина')),
                ('group', models.ManyToManyField(to='core.Group', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_favourites', to='core.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Список избранного',
                'verbose_name_plural': 'Список избранного',
                'ordering': ('user',),
            },
        ),
        migrations.AddField(
            model_name='card',
            name='shop',
            field=models.ManyToManyField(help_text='Выберите магазин', to='core.Shop', verbose_name='Магазин'),
        ),
        migrations.AddConstraint(
            model_name='favourites',
            constraint=models.UniqueConstraint(fields=('user', 'card'), name='uniq_favorites'),
        ),
    ]
