# Generated by Django 3.2.22 on 2023-11-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
        migrations.AddField(
            model_name='card',
            name='group',
            field=models.ManyToManyField(to='core.Group', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(default=1, help_text='Введите название магазина', max_length=20, verbose_name='Название магазина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления карты'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='Введите название категории', max_length=20, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(help_text='Введите название магазина', max_length=20, verbose_name='Название магазина'),
        ),
    ]
