# Generated by Django 4.1 on 2023-11-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.shop', verbose_name='Магазин'),
        ),
    ]
