# Generated by Django 3.2.22 on 2023-11-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='core.Group', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, default='shop/default.jpg', help_text='Загрузите логотип магазина', null=True, upload_to='shop/', verbose_name='Лого магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(help_text='Назовите магазин', max_length=30, verbose_name='Название магазина'),
        ),
    ]
