# Generated by Django 3.2.22 on 2023-11-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image_gtin',
        ),
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.CharField(default=1, help_text='Введите номер карты', max_length=150, verbose_name='Номер карты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(help_text='Введите название магазина', max_length=20, null=True, verbose_name='Название магазина'),
        ),
    ]
