# Generated by Django 4.1 on 2023-11-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercards',
            options={'ordering': ('user',), 'verbose_name': 'Карта пользователя', 'verbose_name_plural': 'Список карт пользователя'},
        ),
        migrations.AddField(
            model_name='usercards',
            name='favourite',
            field=models.BooleanField(blank=True, default=False, verbose_name='Избранное'),
        ),
    ]
