# Generated by Django 4.1 on 2023-11-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_card_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercards',
            name='owner',
            field=models.BooleanField(blank=True, default=True, verbose_name='Владелец карты'),
        ),
    ]
