# Generated by Django 4.1 on 2023-11-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usercards_options_usercards_favourite'),
        ('core', '0003_auto_20231115_1539'),
    ]

    operations = [
    ]
