# Generated by Django 3.2.22 on 2023-11-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20231106_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(help_text='Назовите карту', max_length=20, verbose_name='Название карты'),
        ),
    ]
