# Generated by Django 4.1 on 2023-11-17 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_user_name'),
        ('core', '0005_alter_shop_group_alter_shop_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='image_card',
            new_name='image',
        ),
        migrations.AddField(
            model_name='card',
            name='users',
            field=models.ManyToManyField(through='core.UserCards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AlterField(
            model_name='usercards',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.card', verbose_name='Карты'),
        ),
        migrations.AlterField(
            model_name='usercards',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
