# Generated by Django 3.2.22 on 2023-11-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_card_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(help_text='Введите название карты', max_length=20, unique=True, verbose_name='Название карты'),
        ),
    ]
