# Generated by Django 4.1 on 2023-11-17 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_image_card_card_image_card_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='Номер штрих-кода'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, upload_to='card/', verbose_name='Изображение карты'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название карты'),
        ),
        migrations.AlterField(
            model_name='card',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='card',
            name='usage_counter',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Количество использований карты'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop/', verbose_name='Лого магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название магазина'),
        ),
    ]
