# Generated by Django 4.1 on 2023-12-11 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_card_card_number_alter_card_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercards',
            options={'ordering': ('-pub_date', 'user', 'card'), 'verbose_name': 'Карта пользователя', 'verbose_name_plural': 'Список карт пользователя'},
        ),
        migrations.AddField(
            model_name='usercards',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления карты'),
        ),
        migrations.AddField(
            model_name='usercards',
            name='shared_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared', to=settings.AUTH_USER_MODEL, verbose_name='Кто поделился картой'),
        ),
    ]
