# Generated by Django 4.1 on 2023-11-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_card_barcode_number_alter_card_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='encoding_type',
            field=models.CharField(blank=True, choices=[('code128', 'CODE128'), ('code39', 'CODE39'), ('upc-a', 'UPC-A'), ('upc-e', 'UPC-E'), ('ean-13', 'EAN-13'), ('ean-8', 'EAN-8'), ('qr-kod', 'QR-код')], default='ean-13', max_length=30, verbose_name='Тип кодировки бар-кода карты'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название карты'),
        ),
    ]
