# Generated by Django 3.2.22 on 2023-11-08 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='group',
            field=models.ManyToManyField(blank=True, to='core.Group', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
