# Generated by Django 4.1 on 2023-11-14 17:48

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20231108_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(blank=True, default=True, verbose_name='Принадлежность')),
            ],
            options={
                'verbose_name': 'Список избранного',
                'verbose_name_plural': 'Список избранного',
                'ordering': ('user',),
            },
        ),
        migrations.RemoveField(
            model_name='card',
            name='group',
        ),
        migrations.RemoveField(
            model_name='card',
            name='owner',
        ),
        migrations.AddField(
            model_name='card',
            name='encoding_type',
            field=models.CharField(choices=[('code128', 'CODE128'), ('code39', 'CODE39'), ('upc-a', 'UPC-A'), ('upc-e', 'UPC-E'), ('ean-13', 'EAN-13'), ('ean-8', 'EAN-8'), ('qr-kod', 'QR-код')], default='ean-13', max_length=30, verbose_name='Тип кодировки бар-кода карты'),
        ),
        migrations.AddField(
            model_name='card',
            name='usage_counter',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Количество использования карты'),
        ),
        migrations.AddField(
            model_name='shop',
            name='color',
            field=models.CharField(blank=True, max_length=16, validators=[core.validators.validate_color_format], verbose_name='Цвет магазина'),
        ),
        migrations.AddField(
            model_name='shop',
            name='validation',
            field=models.BooleanField(blank=True, default=False, verbose_name='Критерий валидации магазина'),
        ),
        migrations.AlterField(
            model_name='card',
            name='barcode_number',
            field=models.CharField(blank=True, help_text='Введите номер штрих-кода', max_length=40, verbose_name='Номер штрих-кода'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(blank=True, help_text='Введите номер карты', max_length=40, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(help_text='Введите название карты', max_length=30, unique=True, verbose_name='Название карты'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(help_text='Назовите карту', max_length=30, verbose_name='Название карты'),
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
        migrations.AddField(
            model_name='usercards',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_favourites', to='core.card', verbose_name='Карты'),
        ),
        migrations.AddField(
            model_name='usercards',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='usercards',
            constraint=models.UniqueConstraint(fields=('user', 'card'), name='uniq_favorites'),
        ),
    ]
