# Generated by Django 4.1 on 2023-12-15 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_card_name_alter_group_name_alter_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=256, validators=[django.core.validators.RegexValidator(message='Номер штрих-кода может содержать только буквы, цифры, пробелы, тире и нижнее подчеркивание.', regex='^[0-9A-Za-zА-Яа-я\\ \\-_]{1,256}$')], verbose_name='Номер штрих-кода'),
        ),
    ]
