# Generated by Django 4.1 on 2023-12-16 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_card_name_alter_group_name_alter_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator("^[A-Za-zА-ЯЁа-яё\\d\\@\\!\\#\\$\\%\\&\\'\\*\\+\\/\\=\\?\\^\\_\\`\\{\\|\\}\\~\\-\\.\\ ]{1,30}$", message='Имя может содержать только буквы, цифры, пробелы и спецсимволы.')], verbose_name='Название карты'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator("^[A-Za-zА-ЯЁа-яё\\d\\@\\!\\#\\$\\%\\&\\'\\*\\+\\/\\=\\?\\^\\_\\`\\{\\|\\}\\~\\-\\.\\ ]{1,30}$", message='Имя может содержать только буквы, цифры, пробелы и спецсимволы.')], verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator("^[A-Za-zА-ЯЁа-яё\\d\\@\\!\\#\\$\\%\\&\\'\\*\\+\\/\\=\\?\\^\\_\\`\\{\\|\\}\\~\\-\\.\\ ]{1,30}$", message='Имя может содержать только буквы, цифры, пробелы и спецсимволы.')], verbose_name='Название магазина'),
        ),
    ]
